name: Add a file to a bucket
'on': push
jobs:
  deploy:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Create bucket and validate if it's already existed
        uses: alialrubaye/aws-s3-create-bucket@v1.0.0
        with:
          bucket-name: my-unique-name-for-my-bucket
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: us-east-1
