name: Add a file to a bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Upload file to bucket
      uses: a-sync/s3-uploader@master
      with:
        args: --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: "s3://github-actions-demo-v1"
        S3_KEY: ${{ secrets.S3_KEY }}
        FILE: "C:/Users/ERJ3KOR/Downloads/dummy.txt"
